# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaspPrintOptionsSetPrintDevInfo <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsSetPrintDevInfo`, value))
}

jaspPrintOptionsGetPrintDevInfo <- function() {
    .Call(`_jaspResults_jaspPrintOptionsGetPrintDevInfo`)
}

jaspPrintOptionsVisibleTableColSep <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsVisibleTableColSep`, value))
}

