# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaspPrintOptionsSetPrintDevInfo <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsSetPrintDevInfo`, value))
}

jaspPrintOptionsGetPrintDevInfo <- function() {
    .Call(`_jaspResults_jaspPrintOptionsGetPrintDevInfo`)
}

jaspPrintOptionsSetVisibleTableColSep <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsSetVisibleTableColSep`, value))
}

jaspPrintOptionsGetVisibleTableColSep <- function() {
    .Call(`_jaspResults_jaspPrintOptionsGetVisibleTableColSep`)
}

jaspPrintOptionsSetIndentSize <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsSetIndentSize`, value))
}

jaspPrintOptionsGetIndentSize <- function() {
    .Call(`_jaspResults_jaspPrintOptionsGetIndentSize`)
}

jaspPrintOptionsSetIndentWithTabs <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsSetIndentWithTabs`, value))
}

jaspPrintOptionsGetIndentWithTabs <- function() {
    .Call(`_jaspResults_jaspPrintOptionsGetIndentWithTabs`)
}

jaspPrintOptionsSetUseUnicode <- function(value) {
    invisible(.Call(`_jaspResults_jaspPrintOptionsSetUseUnicode`, value))
}

jaspPrintOptionsGetUseUnicode <- function() {
    .Call(`_jaspResults_jaspPrintOptionsGetUseUnicode`)
}

